### ISSUE TITLE
Better sound with the Sample Rate of 44100Hz + a lower Resample Quality. 

### ISSUE THREAD

**Issue by PalMusicFan** [usineur/sdlpal#4]
Please submit your issue in English or Chinese.
请使用中文或英文提交问题。

**Is your feature request related to a problem? Please describe. 你的需求是要解决什么问题？请描述一下。**

Now the Sample Rate is 22050Hz in the given sdlpal.cfg. The sound quality of 22050Hz is not so good. 

**Describe the solution you'd like 描述你希望的解决方案**

SampleRate=44100
ResampleQuality=3

Lower Resample Quality could reduce the CPU load.  According to my test, Resample Quality of 3 is acceptable. 0 makes the sound noisy, and 2 is also acceptable, while 1 strangely makes the sound choppy.  

**Describe alternatives you've considered 描述另一个可选的解决方案**

SampleRate=44100
ResampleQuality=2

**Additional context 其他上下文**
请在此追加其他更详细的信息，或者屏幕截图，如果你感觉上面的描述不够直观。

**Comment by usineur** [comment]
Yeah, it seems better.

I just updated the last release with a config file with these options. Thx.
