### ISSUE TITLE
English patch v3.3 is available. Would you please update the instructions? 

### ISSUE THREAD

**Issue by PalMusicFan** [usineur/sdlpal#5]
The English patch v3.3 is available. 
Would you please update the release instructions? 
"Pal98rqp.zip" users should use patch files in the folder of "win_files". 

> [Changelog]
======================
v3.3 20190831 (by Nostaljaded)
 Fixed dialog text styling due to new symbols (not present in original game) being used for text styling (by other mods) in recent SDLPal
 Renamed localization filename extension to SLF (SDLPal Localization File)
 Renamed Lao Lao to Grandma, Miss Liu to Madam Liu, Chief Priestess to Queen, A Nu to Ah Nu, Mentor to Master Ling Yue & other minor characters
 Fixed NPCs not properly named for a village in the latter half
 Another pass on minor text cleanups for more faithful translation
 Other minor text cleanups @ 55%

Could I expect a new Vita version release? Thanks!

**Comment by usineur** [comment]
Done, release 1.3 is now available.
